# Generated by Django 4.0.3 on 2022-04-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('1', 'Prospecting'), ('2', 'Analysis'), ('3', 'Proposal'), ('4', 'Negotiation'), ('5', 'Closed Won'), ('0', 'Closed Lost')], default=1, max_length=2),
        ),
    ]
